skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
quantum_invest = "77AAyYrg2o34w4xS3wAtsLHaWnKWLUdFPbaruKzefBuG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
